sudo: false
language: android
jdk: oraclejdk8

licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - build-tools-25.0.1
    - extra-android-m2repository
    - android-25

script:
   - ./gradlew build connectedCheck

before_install:
  - sh ci/emulator.sh
  - bash ci/.travis_android_license_bugfix.sh

after_script:
  - adb logcat -d

after_success:
  - bash <(curl -s https://codecov.io/bash)