sudo: false
language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.1
    - extra-android-m2repository
    - android-25

script:
   - ./gradlew build connectedCheck

before_install:
  - sh ci/emulator.sh

after_script:
  - adb logcat -d

after_success:
  - bash <(curl -s https://codecov.io/bash)